### PR TITLE
Script to update annotations

### PR DESCRIPTION
**Pull request by kusalananda**
The script takes the pathname of a CSV or XLSX (Microsoft Excel spreadsheet) file on the command line and updates the annotations in the database from it.  This affects only the `taxon_annotation` table. Old annotations on the affected sequences will have their `status` field changed to `old` and newly inserted annotations will have a `status` of `valid`.  Sequences in the provided file that are *not* found in the database will be flagged for the user, and skipped.

### CODE REVIEW

**Comment by kusalananda** [comment]
I'm turning this into a draft PR again while I make a few changes that makes the script not depend on `csvkit` on the host (hopefully).

**Comment by kusalananda** [comment]
Right, should be good to review now.  Thanks to @pontus and @norling for input.

**Comment by pragermh** [comment]
Thanks @kusalananda. This works well, as far as I can tell :thumbsup: Due to downstream processing, I need empty taxonomy ranks to be added as empty strings rather than null values, though (not ideal, but easiest for now), please.

**Comment by kusalananda** [comment]
> Thanks @kusalananda. This works well, as far as I can tell 👍 Due to downstream processing, I need empty taxonomy ranks to be added as empty strings rather than null values, though (not ideal, but easiest for now), please.

I'll sort this out ASAP.

**Comment by pragermh** [comment]
Sorry, but I meant the different ranks, i.e. columns 'kingdom', 'phyla', 'class', 'order', 'family', 'genus', 'specificEpithet' and 'infraspecificEpithet'. Sometimes an ASV is only determined on higher taxonomic level, e.g. 'family', and then lower ranks e.g. 'genus', are blank, but I need them to be empty string ''.




<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:////Users/maria.prager/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel="File-List" href="file:////Users/maria.prager/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>





kingdom | phylum | class | order | family | genus | specificEpithet | infraspecificEpithet | otu
-- | -- | -- | -- | -- | -- | -- | -- | --












<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:////Users/maria.prager/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel="File-List" href="file:////Users/maria.prager/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>





kingdom | phylum | class | order | family | genus | specificEpithet | infraspecificEpithet | otu
-- | -- | -- | -- | -- | -- | -- | -- | --












<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:////Users/maria.prager/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel="File-List" href="file:////Users/maria.prager/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>





kingdom | phylum | class | order | family | genus | specificEpithet | infraspecificEpithet | otu
-- | -- | -- | -- | -- | -- | -- | -- | --












<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:////Users/maria.prager/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel="File-List" href="file:////Users/maria.prager/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>





kingdom | phylum | class | order | family | genus | specificEpithet | infraspecificEpithet | otu
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by kusalananda** [comment]
> Sorry, but I meant the different ranks, i.e. columns 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'specificEpithet' and 'infraspecificEpithet'. Sometimes an ASV is only determined on higher taxonomic level, e.g. 'family', and then lower ranks e.g. 'genus', are blank, but I need them to be empty string ''.

Does that mean that the specific column `taxon_rank` _could_ be `NULL` but the others that you've mentioned now shouldn't be `NULL`? Since I have no idea of what a "rank" is and what is considered a lower or higher rank, would you mind spelling out _exactly_ what columns need to be empty rather than `NULL`?

**Comment by pragermh** [comment]
OK: 

If any of the following are null / missing value in the annotation file: 
'kingdom',  'phylum',  'class',  'order',  'family',  'genus',  'specificEpithet' , 'infraspecificEpithet' and 'otu', 
they should be inserted as empty string '' in the db. 

The only other field that should be allowed to be null / missing value in the annotation file is 'taxon_remarks', and that should, in that case, be inserted as null into the db.

All other fields should have non-null values in the annotation file.

**Pull request merged**
