### PR TITLE
Enable limiting DB access by providing environment variable DBACCESS

### PR DESCRIPTION
**Pull request by pontus**

### CODE REVIEW

**Comment by pragermh** [comment]
Thanks @pontus. I haven't tested this on the server yet, as SBDI colleagues are supposed to have a first look at the app this week, and I guess I can't really test it locally, right? I'm a bit confused regarding the 'workflow' for changes here. I guess I need to:
1. Add IPs to DBACCESS variable in .env file
2. Rebuild postgres service for .env changes to take effect
3. Execute restrict_db_access.sh inside running postgres container to apply changes to pg_hba.conf
4. Restart postgres service again for pg_hba.conf changes to take effect [or send a SIGHUP signal, according to info in pg_hba.conf:
# This file is read on server startup and when the server receives a
# SIGHUP signal.  If you edit the file on a running system, you have to
# SIGHUP the server for the changes to take effect, run "pg_ctl reload",
# or execute "SELECT pg_reload_conf()"].
Have I misunderstood this? If not, would it be possible to just automate 2-4 somehow, i.e. so that I just change DBACCESS when I need to, and this variable is used whenever I start postgres service?

**Comment by pontus** [comment]
Sorry, I probably should have added some info about that.

So, to test one would need to stop services and remove the database (the init files are only applied when given a clean slate - if a database exists already, it won't touch them).

With that done, starting with a `DBACCESS` variable set in `.env` would cause the limits to apply.

There is (at least now) no need to rebuild - these files are bound in from the outside by the docker-compose file(s).

(It's probably helpful to have fairly liberal hosts access, at least while testing, e.g.
`127.0.0.1/8 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8`.)

**Comment by pontus** [comment]
(And that may have been unclear; if you want to test without removing your database, the flow would be something like that - you still don't have to rebuild the container but need to restart it, then execute the script and then make sure the database is restarted again.

The easiest way to make sure the database is restricted is probably to restart the container (`docker restart asv-db`).

**Comment by pragermh** [comment]
Summarised your responses in README.md but then noticed that restarting asv-db doesn't change DBACCESS inside the container and the script thus has no effect. What I did was:
[edit DBACCESS in .env]
```
docker restart asv-db
docker exec asv-db docker-entrypoint-initdb.d/04-restrict-db.sh
docker restart asv-db
```
So what did I get wrong?

**Comment by pontus** [comment]
Ah, yes, it won't pick up changed environment without stop then start to docker-compose.

One option can be to pass it to docker exec e.g. `docker exec -e DBACCESS='127.0.0.1/8 1.1.1.1/32' asv-db docker-entrypoint-initdb.d/04-restrict-db.sh`

(Note that particular example will not allow your main container access and thus break things.)

**Comment by pragermh** [comment]
Seems it doesn't break anything as it only adds IP:s, i.e. nothing is removed.

**Comment by pontus** [comment]
That's odd (the `sed` line should delete stuff). What does the `pg_hba.conf` look like after running?

**Comment by pragermh** [comment]
host all all 127.0.0.1/8 md5
host all all 192.168.0.0/16 md5
host all all 172.16.0.0/12 md5
host all all 10.0.0.0/8 md5
host all all 127.0.0.1/8 md5
host all all 1.1.1.1/32 md5
host all all all reject

**Comment by pragermh** [comment]
I think I did a 
```
docker-compose stop
docker-compose up
docker exec asv-db docker-entrypoint-initdb.d/04-restrict-db.sh
Adding 127.0.0.1/8 to allowed IP:s
Adding 192.168.0.0/16 to allowed IP:s
Adding 172.16.0.0/12 to allowed IP:s
Adding 10.0.0.0/8 to allowed IP:s
```
Then:
```
docker exec -e DBACCESS='127.0.0.1/8 1.1.1.1/32' asv-db docker-entrypoint-initdb.d/04-restrict-db.sh
Adding 127.0.0.1/8 to allowed IP:s
Adding 1.1.1.1/32 to allowed IP:s
```

**Comment by pontus** [comment]
That looks good. 

And no, specific previously allowed networks are not removed if that was what was expected (this would only be run on the first run anyway).

**Comment by pragermh** [comment]
OK, so let's say I have a running application on the server, and then the IPT tool which will connect to our postgres db is migrated from IP X to IP Y. How would I remove X and add Y with minimal disturbance to services? Preferrably not having to remove and re-add the db, I mean. Perhaps you could list the commands for this?

**Comment by pontus** [comment]
The easiest way would likely be to edit with whatever editor is easiest (the one you're most confident with, e.g. `vim`, `nano` or `emacs`; none of these are installed but can be brought into the running container with `apt update; apt install vim nano emacs-nox`) and then running that editor to edit `$PGDATA/pg_hba.conf`).

Also note that if this can often be avoided by giving a less specific netmask (the number after / is the netmask, specifying how many bits from the address should be checked). If you think there might be a risk of servers moving, it's likely even a good idea to use network/netmasks that would include all of them (with the possible exception of switching IP ranges completely in which case one would list the respective networks separately).

**Comment by pontus** [comment]
The easiest way would likely be to edit with whatever editor is easiest (the one you're most confident with, e.g. `vim`, `nano` or `emacs`; none of these are installed but can be brought into the running container with `apt update; apt install vim nano emacs-nox`) and then running that editor to edit `$PGDATA/pg_hba.conf`).

Also note that if this can often be avoided by giving a less specific netmask (the number after / is the netmask, specifying how many bits from the address should be checked). If you think there might be a risk of servers moving, it's likely even a good idea to use network/netmasks that would include all of them (with the possible exception of switching IP ranges completely in which case one would list the respective networks separately).

**Comment by pontus** [comment]
Note; removing old entries are not good, but not critical.

**Comment by pragermh** [comment]
OK, so unless I want to remove an old (allowed) address, I can use the script. Let's leave it at that.

**Comment by pragermh** [comment]
Think this will work for me now (and will test it on server next week), but noticed I get an error when restoring db. It seems to be related to DBACCESS variable, perhaps because it contains whitespace?
```
./backup.sh restore
.env: line 13: 192.168.0.0/16: No such file or directory
```
Tried escaping, but this messed up asv-db initialisation instead:
` DBACCESS=127.0.0.1/8\ 192.168.0.0/16\ 10.0.0.0/8\ 172.16.0.0/12`

**Pull request merged**
