### PR TITLE
Feature/delete dataset

### PR DESCRIPTION
**Pull request by kusalananda**
Schema changes and script to facilitate easy deletion of datasets.

The schema changes amounts to adding `ON DELETE CASCADE` to foreign key declarations, which makes deletion of rows in a referenced table automatically delete the referring rows in the current table. The actual SQL to delete a dataset and all associated data then becomes trivial.

The script provides an interactive way of seeing the datasets currently available in the `asv-db` container and to delete the one(s) that should no longer be there. It would be wise to do a database backup using the `database-backup.sh` script before actually deleting anything.

### CODE REVIEW

**Comment by kusalananda** [comment]
**Issue:** Deleting all datasets will still leave data in the tables `asv` and `taxon_annotation`.  This is because these tables don't have foreign keys that can be traced back to the `dataset` table.  I suppose this needs to be this way since the schema assumes that a single `asv` entry may be referenced by _multiple_ datasets and that it therefore can't be deleted just because a dataset that referred to it happens to disappear.

**Comment by pragermh** [comment]
Yes, you're right. What we could perhaps do is to delete all asv:s & annotations that are no longer referenced by _any_ dataset, after deleting a specific dataset. Would that work?

**Comment by kusalananda** [comment]
> Yes, you're right. What we could perhaps do is to delete all asv:s & annotations that are no longer referenced by _any_ dataset, after deleting a specific dataset. Would that work?

I think I could make that work, yes.

**Comment by kusalananda** [comment]
Now ready for review I think.

**Pull request merged**
