### PR TITLE
Addition of ipt role

### PR DESCRIPTION
**Pull request by pontus**
New role `ipt` with access to `public` schema as well as `dwc_oc_occurrence`, `dwc_oc_emof` and `dwc_oc_mixs` in `api`.

### CODE REVIEW

**Comment by pragermh** [comment]
Thanks. I got permission errors on the file _setup-env-extra.sh_ but after setting permissions to same as for _restrict_db_access.sh_ I now get:
```
asv-db          | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/00-setup-env-extra.sh
asv-db          | /docker-entrypoint-initdb.d/00-setup-env-extra.sh: line 3: file_env: command not found
asv-db          | /docker-entrypoint-initdb.d/00-setup-env-extra.sh: line 4: file_env: command not found
```
Can't find any useful info on file_env so not sure how to fix this.

**Comment by pontus** [comment]
Sorry, maybe this needs to be documented clearer.

So, all these files (in `db`) are intended to set things up on start.

The startup procedure will look at the permissions of scripts and run those with execute permissions ("in a new environment") and `source` the ones without execute permissions (so it happens in the "same" environment as the entrypoint script).

For this one, it's important that it's in the same environment, so it can not have execute (+x).

if this is desired for changing the setup of a configured server, that can be done but will look different, should we add that as well?

**Comment by pontus** [comment]
Interactively, it will be something like (not tested)

```
POSTGRES_IPT_PASS=$(cat $POSTGRES_IPT_PASS_FILE)
PGRST_DB_ANON_PASS=$(cat $PGRST_DB_ANON_PASS_FILE)
POSTGRES_PASSWORD=$(cat $POSTGRES_PASSWORD_FILE)
export POSTGRES_IPT_PASS  PGRST_DB_ANON_PASS POSTGRES_PASSWORD
psql --username "$POSTGRES_USER" --no-password --dbname "$POSTGRES_DB" -f /docker-entrypoint-initdb.d/03-roles.sql

```

**Comment by pragermh** [comment]
Starting over, discarding the permission change, I still get:
`/usr/local/bin/docker-entrypoint.sh: line 160: /docker-entrypoint-initdb.d/00-setup-env-extra.sh: Permission denied `
- but if I understand you correctly, that is fine because it should be sourced not executed.
However, I only get one user (asv) and no api schema in my db. Perhaps I need to run the interactive section (or similar) but I suspect there is some misunderstanding here, so will try to explain the purpose better:

I just want the role ipt to be created together with role asv when I initialise the db. I don't need to change it later. I really just want a low-permission role to use for login and access to those three views in the IPT tool, so that I don't have to use the more powerful asv role for that (as the db connection will be somewhat accessible to data contributors). So is there anyway to just add this to the initialisation (i.e. whenever I start up with db removed)?

**Comment by pontus** [comment]
Yes, that works for me with the contents in this branch (and should be the case if you remove the database or clone the repo to a new directory, switch branch and bring things up.)

**Comment by pragermh** [comment]
Weird... I remove the postgres-data folder and run`docker-compose build --no-cache && docker-compose up` and can see that the db-folder is re-added but then get:
```

asv-db          | CREATE DATABASE
asv-db          | 
asv-db          | 
asv-db          | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/00-setup-env-extra.sh
asv-db          | /usr/local/bin/docker-entrypoint.sh: line 160: /docker-entrypoint-initdb.d/00-setup-env-extra.sh: Permission denied
asv-db          | 
asv-db          | PostgreSQL Database directory appears to contain a database; Skipping initialization

```

**Comment by pragermh** [comment]
What does your log say in the corresponding section?

**Comment by pontus** [comment]
```
asv-db          | /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/00-setup-env-extra.sh       
```

How do the permissions look for `db/setup-env-extra.sh`, and how do they look for `/docker-entrypoint-initdb.d/00-setup-env-extra.sh` in the container?

[molmod.txt](https://github.com/biodiversitydata-se/mol-mod/files/6324290/molmod.txt)

**Comment by pragermh** [comment]
Both are -rw-r--r--

**Pull request merged**
